export type Faq={q:string;a:string};
export type FaqCategory={id:string;label:string;short:string;faqs:Faq[]};
export const faqCategories:FaqCategory[]=[
{id:"general",label:"General & Company",short:"General",faqs:[
{q:"What services does TreeQ Power provide?",a:"TreeQ Power provides engineering, electromechanical and technical services covering electrical systems, MEP, industrial automation, testing and inspection, maintenance, asset integrity, energy solutions and related technical field services."},
{q:"Where is TreeQ Power located?",a:"TreeQ Power Electromechanical Works LLC is based in Dubai, United Arab Emirates, with its warehouse located in Al Qusais 3, Dubai."},
{q:"When was TreeQ Power established?",a:"TreeQ Power was established in 2002."},
{q:"What industries does TreeQ Power support?",a:"Technical requirements are supported across oil and gas, industrial facilities, commercial developments, infrastructure and utilities, depending on project scope and requirements."},
{q:"Does TreeQ Power provide engineering and technical services?",a:"Yes. Capabilities include engineering and design, technical consultancy, electrical site services, testing and inspection, automation, maintenance, asset integrity and energy-related solutions."},
{q:"Can TreeQ Power support a project from engineering through commissioning?",a:"Yes. Depending on project requirements, support can cover engineering and design, supply, installation, testing, commissioning, operation and maintenance, refurbishment and technical field services."},
{q:"Does TreeQ Power provide maintenance services?",a:"Yes. Maintenance support can cover electrical equipment, power systems, automation, generators, UPS and batteries, switchgear and other technical assets, subject to the required scope."},
{q:"Does TreeQ Power provide site-based technical services?",a:"Yes. Technical field services can include installation, testing, commissioning, inspection, troubleshooting, maintenance and other site activities."},
{q:"Can TreeQ Power support existing electrical installations?",a:"Yes. Existing installations can be assessed for testing, troubleshooting, maintenance, refurbishment, retrofit, power-quality issues and other engineering requirements."},
{q:"How can I request a service from TreeQ Power?",a:"Requirements can be submitted through the website enquiry form on the contact page, or discussed directly by phone so the required scope can be reviewed."}]},
{id:"engineering",label:"Engineering & Design",short:"Engineering",faqs:[
{q:"What does electrical engineering and design include?",a:"Electrical engineering and design can include system studies, equipment sizing, protection coordination, cable and termination schedules, layouts, power-quality studies, earthing design and other project-specific engineering activities."},
{q:"Does TreeQ Power provide power-system studies?",a:"Yes. Power-system engineering capabilities can include load-flow, short-circuit, protection coordination, harmonic analysis, voltage-drop and other electrical studies based on project requirements."},
{q:"What is a load-flow study?",a:"A load-flow study evaluates electrical system voltages, currents, power flows and loading conditions to help assess system performance and equipment loading."},
{q:"What is a short-circuit study?",a:"A short-circuit study calculates prospective fault currents at relevant points in an electrical system to support equipment selection and protection-system design."},
{q:"What is protection coordination?",a:"Protection coordination is the process of selecting and setting protective devices so that faults are isolated appropriately while maintaining system selectivity and continuity where possible."},
{q:"Does TreeQ Power support ETAP-based studies?",a:"Engineering capabilities include electrical system studies and analysis. Specific software availability is confirmed according to the project requirement."},
{q:"What is a harmonic analysis?",a:"Harmonic analysis evaluates waveform distortion caused by nonlinear loads and helps identify potential impacts on electrical equipment, power quality and system performance."},
{q:"What is an arc-flash study?",a:"An arc-flash study evaluates electrical incident-energy risks and helps establish appropriate protection, equipment requirements, operating procedures and safety measures."},
{q:"Does TreeQ Power provide electrical design review?",a:"Yes. Electrical design review can assess system configuration, equipment sizing, protection, cable selection, drawings and other technical aspects according to project requirements."},
{q:"Can TreeQ Power support substation engineering?",a:"Yes. Substation-related engineering can include equipment, protection and control, power systems, auxiliary systems and project-specific engineering support."}]},
{id:"site-services",label:"Electrical Site Services",short:"Site services",faqs:[
{q:"What are electrical site services?",a:"Electrical site services include activities such as installation, inspection, testing, commissioning, troubleshooting, maintenance and technical field support."},
{q:"Does TreeQ Power provide electrical installation services?",a:"Yes. Electrical installation support can include power equipment, switchgear, panels, cables, control systems and associated electrical infrastructure."},
{q:"Does TreeQ Power provide electrical testing and commissioning?",a:"Yes. Testing and commissioning services can be provided for electrical equipment and systems according to the applicable project requirements and standards."},
{q:"What electrical equipment can be serviced?",a:"Depending on scope, services can cover switchgear, transformers, motors, generators, protection systems, MCCs, VFDs, UPS systems, batteries, control panels and other electrical equipment."},
{q:"Does TreeQ Power provide electrical troubleshooting?",a:"Yes. Technical troubleshooting can be performed to investigate equipment faults, operational issues, electrical abnormalities and other site problems."},
{q:"What is thermographic inspection?",a:"Thermographic inspection uses infrared imaging to identify abnormal temperature patterns that may indicate loose connections, overloads, component deterioration or other electrical issues."},
{q:"Can TreeQ Power perform power-quality assessments?",a:"Yes. Power-quality assessments can investigate issues such as harmonics, voltage variations, power factor and other electrical performance conditions."},
{q:"Does TreeQ Power provide earthing testing?",a:"Yes. Earthing-related inspection and measurement can be performed according to the applicable system and project requirements."},
{q:"Does TreeQ Power provide lightning-protection services?",a:"Yes. Services can include assessment, design support, installation, inspection and maintenance of earthing and lightning-protection systems according to project requirements."},
{q:"Can TreeQ Power support electrical refurbishment projects?",a:"Yes. Existing electrical systems can be assessed for refurbishment, retrofit, replacement and modernization requirements."}]},
{id:"testing",label:"Testing, Inspection & Commissioning",short:"Testing",faqs:[
{q:"What testing services does TreeQ Power provide?",a:"Testing capabilities can include electrical equipment testing, power-quality analysis, thermography, insulation testing, circuit-breaker testing, battery testing, transformer testing and other project-specific tests."},
{q:"What is primary injection testing?",a:"Primary injection testing involves applying current directly through the primary circuit of equipment to verify protection and associated electrical functions."},
{q:"What is secondary injection testing?",a:"Secondary injection testing applies controlled signals to protection-system inputs to verify relay operation, settings and protection logic."},
{q:"What is circuit-breaker testing?",a:"Circuit-breaker testing evaluates mechanical and electrical performance, including operating times, contact resistance and other applicable parameters."},
{q:"What is insulation-resistance testing?",a:"Insulation-resistance testing measures the resistance of electrical insulation to help identify deterioration, moisture, contamination or other insulation-related conditions."},
{q:"Does TreeQ Power provide transformer testing?",a:"Transformer testing can be provided according to the transformer type, project requirements and applicable testing procedures."},
{q:"Does TreeQ Power provide testing-equipment rental?",a:"Yes. Testing equipment can be available for rental depending on equipment type, availability and project requirements."},
{q:"What testing equipment can be rented?",a:"Equipment may include power-quality analyzers, thermography cameras, primary-injection equipment, contact-resistance testers, battery load banks, insulation-resistance testers, earth testers and other electrical testing equipment."},
{q:"What is third-party inspection?",a:"Third-party inspection provides independent technical inspection, verification or testing support for equipment, materials, installations or project activities according to the agreed scope."},
{q:"Does TreeQ Power provide NDT-related inspection services?",a:"Inspection capabilities may include non-destructive testing methods such as ultrasonic, radiographic, magnetic-particle, dye-penetrant and visual techniques, subject to project scope and qualified personnel availability."}]},
{id:"asset-integrity",label:"Asset Integrity & RBI",short:"Asset integrity",faqs:[
{q:"What is asset integrity?",a:"Asset integrity is the systematic management of equipment and infrastructure to help ensure that assets remain safe, reliable and fit for their intended service throughout their operating life."},
{q:"What is Asset Integrity Management?",a:"Asset Integrity Management is a structured approach for managing asset condition, risks, inspection, maintenance and integrity-related activities throughout the asset lifecycle."},
{q:"What is Risk-Based Inspection (RBI)?",a:"Risk-Based Inspection is a systematic approach that prioritizes inspection activities according to the likelihood and consequence of potential equipment failure."},
{q:"Why is RBI important?",a:"RBI helps organizations focus inspection resources on equipment and failure mechanisms associated with higher levels of risk, while supporting safety, reliability and efficient inspection planning."},
{q:"Which industries can use RBI?",a:"RBI can be relevant to industries such as oil and gas, petrochemical, power, utilities, chemical processing and other facilities with significant fixed or process equipment integrity requirements."},
{q:"What information is required for an RBI assessment?",a:"Depending on scope, information can include equipment data, operating conditions, materials, inspection history, corrosion information, failure history, process information and relevant design documentation."},
{q:"What are the main outputs of an RBI study?",a:"Outputs may include risk rankings, inspection strategies, inspection plans, risk-control recommendations, equipment priorities and supporting integrity documentation."},
{q:"What is an integrity operating window?",a:"An integrity operating window defines operating parameters or limits that help control conditions capable of affecting equipment integrity."},
{q:"What is asset integrity assessment?",a:"Asset integrity assessment evaluates the condition, risks, degradation mechanisms and remaining integrity considerations of an asset or equipment group."},
{q:"Can RBI help optimize inspection resources?",a:"Yes. RBI can help prioritize inspection activities according to risk, allowing inspection resources to be focused where they provide the greatest risk-management value."}]},
{id:"power-systems",label:"Power Systems & Switchgear",short:"Power systems",faqs:[
{q:"What is HV/MV switchgear?",a:"HV/MV switchgear is electrical equipment used to control, protect, isolate and distribute electrical power at high- and medium-voltage levels."},
{q:"What switchgear solutions does TreeQ Power support?",a:"Solutions can include medium-voltage switchgear, gas-insulated equipment, ring-main units, protection systems, capacitor banks, MV drives, busducts and associated electrical equipment."},
{q:"What is an RMU?",a:"An RMU, or Ring Main Unit, is compact medium-voltage switchgear commonly used for distribution networks and ring-main electrical systems."},
{q:"What is LV switchgear?",a:"LV switchgear consists of equipment used to control, distribute, protect and isolate low-voltage electrical systems."},
{q:"What LV panels can TreeQ Power support?",a:"Depending on project requirements, solutions can include MDBs, SMDBs, FDBs, MCCs, ATS panels, synchronizing panels, feeder pillars, capacitor panels and control panels."},
{q:"What is a busduct?",a:"A busduct is an enclosed electrical distribution system using busbars to transfer electrical power between equipment or distribution points."},
{q:"What is an MCC?",a:"An MCC, or Motor Control Center, is a centralized assembly used to control and protect multiple electric motors and associated equipment."},
{q:"What are protection relays?",a:"Protection relays monitor electrical parameters and initiate protective actions when abnormal or fault conditions are detected."},
{q:"Does TreeQ Power support switchgear maintenance?",a:"Yes. Switchgear maintenance can include inspection, testing, troubleshooting, servicing, refurbishment and other maintenance activities according to equipment and project requirements."},
{q:"Can TreeQ Power support transformer-related requirements?",a:"Yes. Transformer-related services can include engineering support, testing, inspection, maintenance and associated electrical services depending on transformer type and project scope."}]},
{id:"automation",label:"Automation & Instrumentation",short:"Automation",faqs:[
{q:"What is industrial automation?",a:"Industrial automation uses control systems, instrumentation and software to monitor and control industrial processes and equipment."},
{q:"What automation systems does TreeQ Power support?",a:"Capabilities can include PLC, RTU, SCADA, HMI, VFD, soft-starter, control-panel and industrial communication systems."},
{q:"What is a PLC?",a:"A PLC, or Programmable Logic Controller, is an industrial control computer used to monitor inputs and control machines, equipment and processes."},
{q:"What is SCADA?",a:"SCADA stands for Supervisory Control and Data Acquisition. It provides centralized monitoring, data acquisition and supervisory control of industrial systems."},
{q:"What is an HMI?",a:"An HMI, or Human-Machine Interface, provides an interface through which operators can monitor and interact with machines and industrial processes."},
{q:"What is a VFD?",a:"A VFD, or Variable Frequency Drive, controls motor speed and torque by varying the frequency and voltage supplied to an electric motor."},
{q:"Does TreeQ Power provide automation panel services?",a:"Yes. Automation-related services can include panel engineering, assembly, software development, testing, installation and commissioning according to project requirements."},
{q:"What instrumentation services are available?",a:"Instrumentation support can include engineering, supply, installation, testing and services for process measurement, control instruments, valves and related systems."},
{q:"Which industries use industrial automation?",a:"Industrial automation can support oil and gas, chemical and petrochemical facilities, utilities, power, manufacturing, infrastructure and other process industries."},
{q:"Does TreeQ Power support PLC and SCADA commissioning?",a:"Yes. PLC, SCADA and related control systems can be supported during installation, testing and commissioning according to the project scope."}]},
{id:"generators",label:"Generators, Load Banks, Batteries & UPS",short:"Generators & UPS",faqs:[
{q:"Does TreeQ Power provide generator rental services?",a:"Generator rental can be provided depending on generator capacity, availability, project duration and site requirements."},
{q:"What generator capacities are available?",a:"Generator capacities depend on current availability and project requirements. Different capacity ranges can be considered for temporary and project-specific power requirements."},
{q:"What is a load bank?",a:"A load bank is equipment used to apply a controlled electrical load to a generator, UPS or other power source for testing and performance verification."},
{q:"Why is generator load-bank testing important?",a:"Load-bank testing can verify generator performance under controlled load conditions and help identify issues that may not appear during no-load operation."},
{q:"Does TreeQ Power provide load-bank testing?",a:"Load-bank testing services can be provided according to generator capacity, site conditions and project requirements."},
{q:"What generator services are available?",a:"Services may include rental, supply, installation, testing, commissioning, maintenance, troubleshooting and load-bank testing."},
{q:"What is a UPS?",a:"A UPS, or Uninterruptible Power Supply, provides backup power and power conditioning for connected electrical or electronic equipment during interruptions or disturbances."},
{q:"What battery systems does TreeQ Power support?",a:"Battery-related solutions can include industrial battery systems, battery chargers and UPS-associated battery systems depending on project requirements."},
{q:"Why are batteries important in critical electrical systems?",a:"Battery systems provide stored energy for backup and control functions in applications where continuity of electrical supply is important."},
{q:"Does TreeQ Power provide UPS maintenance?",a:"UPS maintenance and associated technical support can be provided according to the equipment type, site requirements and agreed maintenance scope."}]},
{id:"mep",label:"MEP, HVAC & Building Technologies",short:"MEP & HVAC",faqs:[
{q:"What MEP services does TreeQ Power provide?",a:"MEP capabilities can include mechanical, electrical and plumbing consultancy and technical support, along with HVAC, building technologies and energy-related services."},
{q:"What HVAC systems can TreeQ Power support?",a:"HVAC capabilities can include chillers, cooling towers, AHUs, FAHUs, FCUs, ventilation systems, packaged units, pumps, ductwork and related systems."},
{q:"Does TreeQ Power provide HVAC engineering?",a:"Yes. HVAC engineering can include heat-load assessment, system design, equipment selection, engineering support and project-specific technical services."},
{q:"What are building technologies?",a:"Building technologies can include systems such as fire detection, voice evacuation, emergency lighting, CCTV, access control, structured cabling, public address and intelligent building controls."},
{q:"Does TreeQ Power support fire alarm systems?",a:"Fire detection and alarm-related solutions can be supported according to project requirements, applicable standards and approved system specifications."},
{q:"What is emergency lighting?",a:"Emergency lighting provides illumination during normal power failure or emergency conditions to support safe movement and evacuation."},
{q:"Does TreeQ Power provide lighting solutions?",a:"Yes. Lighting solutions can include indoor, outdoor, architectural, industrial and application-specific lighting along with lighting-control requirements."},
{q:"What are lighting controls?",a:"Lighting controls are systems used to manage lighting operation, such as switching, dimming, scheduling, occupancy-based control and intelligent control systems."},
{q:"Does TreeQ Power support ELV systems?",a:"ELV capabilities can include CCTV, access control, structured cabling, public-address systems, intercom and other low-voltage building technology systems, subject to project scope."},
{q:"Can TreeQ Power support building refurbishment projects?",a:"Yes. Existing buildings and systems can be assessed for electrical, HVAC, building technology, energy-efficiency and refurbishment requirements."}]},
{id:"energy",label:"Energy, Sustainability & Renewable Energy",short:"Energy",faqs:[
{q:"What are energy audits?",a:"Energy audits evaluate how energy is consumed within a facility and identify potential opportunities for improving efficiency, reducing losses and managing energy costs."},
{q:"Does TreeQ Power provide energy-management services?",a:"Energy-related services can include energy auditing, energy-performance assessment, benchmarking, measurement and verification support and efficiency improvement studies."},
{q:"What is sustainable building design?",a:"Sustainable building design integrates energy efficiency, resource efficiency, environmental considerations, lifecycle performance and occupant requirements into building design and operation."},
{q:"Does TreeQ Power support energy-efficient lighting?",a:"Yes. Energy-efficient lighting solutions and lighting-control strategies can be considered as part of electrical and energy-efficiency projects."},
{q:"What is renewable energy?",a:"Renewable energy is energy generated from naturally replenishing sources such as sunlight, wind and other renewable resources."},
{q:"Does TreeQ Power provide solar-energy solutions?",a:"Solar-related solutions can include photovoltaic systems, solar structures, batteries, inverters, solar lighting and project-specific solar applications, subject to scope and availability."},
{q:"What is a rooftop solar PV system?",a:"A rooftop solar PV system uses photovoltaic modules installed on a building roof to convert sunlight into electrical energy."},
{q:"What is an on-grid solar system?",a:"An on-grid solar system is connected to the electrical grid and can supply generated solar power to the facility while interacting with the grid according to the applicable system design and regulations."},
{q:"Can TreeQ Power support energy-efficiency improvements?",a:"Yes. Energy audits, power-quality assessments, efficient lighting, automation, system optimization and other engineering measures can be evaluated to identify potential efficiency improvements."},
{q:"How can I discuss an energy, electrical or asset-integrity requirement with TreeQ Power?",a:"Requirements can be submitted through the website enquiry form or discussed directly by phone. Providing the site location, equipment details, technical issue, required service and project timeline helps the engineering team review the requirement."}]}];
export const faqCount=faqCategories.reduce((n,c)=>n+c.faqs.length,0);
export const faqCategoryLinks:Record<string,{label:string;to:string}[]>={
 general:[{label:"Our Services",to:"/our-services"},{label:"About Us",to:"/about-us"},{label:"Contact",to:"/contact"}],
 engineering:[{label:"Engineering & design services",to:"/our-services"},{label:"Solutions",to:"/solutions"}],
 "site-services":[{label:"Electrical site services",to:"/our-services"},{label:"Industries",to:"/industries"}],
 testing:[{label:"Testing & inspection services",to:"/our-services"},{label:"Contact",to:"/contact"}],
 "asset-integrity":[{label:"Asset integrity services",to:"/our-services"},{label:"Oil & gas industries",to:"/industries"}],
 "power-systems":[{label:"Power systems solutions",to:"/solutions"},{label:"Utilities & infrastructure",to:"/industries"}],
 automation:[{label:"Automation solutions",to:"/solutions"},{label:"Industrial facilities",to:"/industries"}],
 generators:[{label:"Generator & load bank services",to:"/our-services"},{label:"Contact",to:"/contact"}],
 mep:[{label:"MEP & building technology solutions",to:"/solutions"},{label:"Commercial developments",to:"/industries"}],
 energy:[{label:"Energy & sustainability solutions",to:"/solutions"},{label:"Contact",to:"/contact"}]};
