import hero from "@/assets/hero.jpg";
import engineering from "@/assets/engineering.jpg";
import field from "@/assets/field.jpg";
import solar from "@/assets/solar.jpg";
import industrial from "@/assets/industrial.jpg";
import powerlines from "@/assets/powerlines.jpg";
import { lib } from "@/lib/image-library";
import { homeImages } from "@/lib/home-images";

export type PageData = { title:string; eyebrow:string; description:string; intro:string; image:string; imageAlt:string; sections:{title:string;body:string;items?:string[]}[]; note?:string };
export const images={hero,engineering,field,solar,industrial,powerlines};
export const navGroups=[
 {label:"About Us",to:"/about-us",items:[{label:"Company Overview",to:"/about-us/company-overview"},{label:"Why TreeQ Power",to:"/about-us/why-treeq-power"},{label:"Certifications",to:"/about-us/certifications"},{label:"Clients & Partners",to:"/about-us/clients-partners"},{label:"Brands",to:"/about-us/brands"},{label:"Testimonials",to:"/about-us/testimonials"}]},
 {label:"Services",to:"/our-services",items:[{label:"Engineering & Design",to:"/our-services/engineering-design"},{label:"Consultancy Services",to:"/our-services/consultancy-services"},{label:"Electrical Site Services",to:"/our-services/technical-field-services-electrical"},{label:"Electronics Repair & Maintenance",to:"/our-services/electronic-repair-maintenance"},{label:"Generator & Load Bank Services",to:"/our-services/generator-load-bank-services"},{label:"Testing Equipment Rental",to:"/our-services/testing-equipment-rental"},{label:"Third-Party Inspection",to:"/our-services/third-party-inspection"},{label:"Cable Fault Location",to:"/our-services/cable-fault-location"},{label:"Green Energy & Sustainable Design",to:"/our-services/green-energy-sustainable-design"},{label:"Earthing & Lightning Protection",to:"/our-services/earthing-lightning-protection"},{label:"Risk-Based Inspection",to:"/our-services/asset-integrity/risk-based-inspection"},{label:"Asset Integrity Assessment",to:"/our-services/asset-integrity/asset-integrity-assessment"},{label:"Inspection Planning",to:"/our-services/asset-integrity/inspection-planning"},{label:"Asset Integrity Management",to:"/our-services/asset-integrity/asset-integrity-management"}]},
 {label:"Solutions",to:"/solutions",items:[{label:"HV Switchgear & Transformers",to:"/solutions/power-systems/hv-switchgear-transformers"},{label:"LV Switchgear & Busducts",to:"/solutions/power-systems/lv-switchgear-busducts"},{label:"Industrial Automation",to:"/solutions/automation-control/industrial-automation"},{label:"Instrumentation",to:"/solutions/automation-control/instrumentation"},{label:"Battery & UPS",to:"/solutions/power-quality/battery-ups"},{label:"HVAC",to:"/solutions/building-technology/hvac"},{label:"Lighting & Lighting Controls",to:"/solutions/building-technology/lighting-controls"},{label:"Building Technologies",to:"/solutions/building-technology/building-technologies"},{label:"Renewable Energy",to:"/solutions/building-technology/renewable-energy"}]},
 {label:"Industries",to:"/industries",items:[{label:"Oil & Gas",to:"/industries/oil-gas"},{label:"Industrial",to:"/industries/industrial"},{label:"Commercial",to:"/industries/commercial"},{label:"Infrastructure",to:"/industries/infrastructure"},{label:"Utilities",to:"/industries/utilities"}]},
 {label:"Resources",to:"/resources/faqs",overview:false,items:[{label:"Blogs",to:"/resources/blogs"},{label:"Downloads",to:"/resources/downloads"},{label:"FAQs",to:"/resources/faqs"}]},
] as const;
const standard=(title:string,eyebrow:string,description:string,intro:string,image:string,items:string[],sectionTitle="Technical scope"):PageData=>({title,eyebrow,description,intro,image,imageAlt:`${title} — TreeQ Power`,sections:[{title:sectionTitle,body:"A coordinated technical scope shaped around the system, site conditions and operating requirement.",items},{title:"From requirement to delivery",body:"TreeQ Power aligns engineering, supply, installation, testing and lifecycle support so technical decisions remain connected throughout delivery."}]});
export const pages:Record<string,PageData>={
 "/about-us":{title:"Engineering confidence across the power lifecycle.",eyebrow:"About TreeQ Power",description:"Meet TreeQ Power, a Dubai-based electrical engineering and electromechanical specialist.",intro:"TreeQ Power Electromechanical Works provides design, engineering, manufacturing, assembly, supply, installation, testing, commissioning, operations and maintenance support across electrical and electromechanical systems.",image:lib.substationYard,imageAlt:"Industrial electrical infrastructure",sections:[{title:"A connected capability",body:"Our scope spans MEP works, switchgear and automation, cable termination and fault location, lighting and controls, HVAC, ELV and fire systems, equipment rental and technical manpower."},{title:"Built around technical needs",body:"We combine engineering analysis with practical field capability to support systems from early studies through operation and maintenance."}]},
 "/about-us/company-overview":standard("A practical engineering partner.","Company overview","TreeQ Power delivers coordinated electrical and electromechanical expertise from Dubai, UAE.","Our work connects engineering, equipment, field execution and asset support into one practical delivery model.",lib.electricalTechnician,["Design and engineering","Manufacturing, assembly and supply","Installation, testing and commissioning","Operations and maintenance","Site and consultancy services"]),
 "/about-us/why-treeq-power":standard("One team. One technical thread.","Why TreeQ Power","A coordinated approach to power systems, field services and asset support.","TreeQ Power is structured to carry technical intent from analysis and design into field execution, verification and long-term support.",lib.switchyardBusbars,["Broad lifecycle coverage","Engineering-led decisions","Specialist testing capability","Integrated power and building solutions"]),
 "/about-us/certifications":{...standard("Credentials should be verified.","Certifications","TreeQ Power certification details will be published after client verification.","The source material references internationally certified technical personnel. Certificate names, numbers, validity and issuing bodies require confirmation before publication.",images.engineering,[]),note:"[CERTIFICATES AND APPROVALS TO BE PROVIDED]"},
 "/about-us/clients-partners":{...standard("Relationships built on technical delivery.","Clients & partners","Approved client and partner information will appear here.","TreeQ Power works across major electrical equipment and automation ecosystems. Formal client and partner relationships must be confirmed before names or logos are displayed.",lib.dubaiTowers,[]),note:"[CLIENT AND PARTNER LOGOS TO BE PROVIDED]"},
 "/about-us/brands":{...standard("Technology and equipment ecosystem.","Brands","Verified manufacturer and technology information will appear here.","TreeQ Power works with equipment and technology across electrical power, automation, drives, controls, instrumentation and industrial systems. Brand relationships and authorization status require client confirmation before publication.",lib.dubaiMarinaDay,[]),note:"[APPROVED BRAND INFORMATION AND LOGOS TO BE PROVIDED]"},
 "/about-us/testimonials":{...standard("Feedback from verified clients.","Testimonials","Approved client feedback will be published here.","Only testimonials confirmed by TreeQ Power and attributed with permission will appear on this page.",lib.constructionSiteSupervision,[]),note:"[APPROVED TESTIMONIALS TO BE PROVIDED]"},
 "/services":standard("Services across the complete project lifecycle.","Services","Explore TreeQ Power engineering, field, testing, sustainability and asset integrity services.","From ETAP-based studies and consultancy to electrical site services, specialist inspection and maintenance, our teams support complex systems from concept through operation.",lib.hvTransformerBank,["Engineering","Field & Maintenance","Testing & Inspection","Sustainability","Asset Integrity"],"Five connected disciplines"),
 "/services/engineering/engineering-design":standard("Engineering & Design","Engineering","Power-system design and studies for coordinated, reliable electrical systems.","TreeQ Power develops the calculations, studies and technical documentation that guide equipment selection, protection and safe system operation.",lib.transmissionGantry,["Load flow and power-flow studies","Short-circuit calculations","Protection coordination and discrimination","Harmonic and power-quality analysis","Voltage-drop and arc-flash studies","Equipment sizing and earthing-grid design","SCADA and substation control systems"]),
 "/services/engineering/consultancy":standard("Consultancy Services","Engineering","Technical consultancy spanning MEP systems, energy performance and project coordination.","Our consultancy scope supports informed design decisions, coordinated specifications and efficient building performance.",lib.dubaiSkylineAerial,["MEP consultancy","Energy modelling","LEED and Estidama-aligned design support","Water treatment systems","Façade performance analysis","Project management consultancy"]),
 "/services/field-maintenance/electrical-site-services":standard("Electrical Site Services","Field & Maintenance","Specialist site support for substation and industrial electrical equipment.","TreeQ Power supports installation, testing, commissioning, troubleshooting and maintenance across HV, MV and LV systems.",lib.substationTransformer,["Substation equipment from 400 kV to 0.415 kV","HV and LV motors","MCC and VFD systems","Testing and commissioning","Remaining-life assessment support","Factory acceptance and third-party inspection"]),
 "/services/field-maintenance/electronics-repair-maintenance":standard("Electronics Repair & Maintenance","Field & Maintenance","Diagnostics and repair support for industrial electronic equipment.","We support the diagnosis, repair and maintenance of electronic assemblies used in industrial control and power applications.",lib.networkCabinet,["Industrial power supplies","PLC modules","Variable-frequency drives","Human-machine interfaces","Control and automation electronics"]),
 "/services/field-maintenance/generator-load-bank-services":standard("Generator & Load Bank Services","Field & Maintenance","Generator rental, testing and maintenance support.","Generator and load-bank services support temporary power, performance verification and planned maintenance requirements.",lib.standbyGenerator,["Generator rental from 15 kVA to 1000 kVA","Load-bank testing","Annual maintenance support","Installation and commissioning assistance","Operational checks"]),
 "/services/testing-inspection/testing-equipment-rental":standard("Testing Equipment Rental","Testing & Inspection","Access specialist electrical testing equipment for planned field work.","TreeQ Power’s documented inventory includes equipment for injection testing, power-quality review, thermal inspection, high-voltage testing and battery assessment.",lib.precisionInstrumentWork,["Primary and secondary injection equipment","Power-quality analyzers","Thermal cameras","High-voltage test equipment","Battery load banks","Cable-fault test equipment"]),
 "/services/testing-inspection/third-party-inspection":standard("Third-Party Inspection","Testing & Inspection","Independent inspection disciplines for equipment, fabrication and critical assets.","Inspection services cover established non-destructive testing methods and welding-quality disciplines supported by appropriately qualified personnel.",lib.weldingFabrication,["Ultrasonic and radiographic testing","Eddy-current testing","Magnetic-particle inspection","Liquid-penetrant and visual testing","Leak and acoustic-emission testing","Infrared thermography","Welding inspection"]),
 "/services/testing-inspection/cable-fault-location":standard("Cable Fault Location","Testing & Inspection","Specialist fault location, testing and repair support for power cables.","TreeQ Power supports systematic cable diagnosis to locate faults, verify insulation condition and restore service.",lib.overheadLineInsulator,["Fault and sheath location up to 132 kV","VLF and DC high-voltage testing","Cable jointing and termination up to 33 kV","Route tracing and identification","Repair and post-repair testing"]),
 "/services/sustainability/green-energy-sustainable-design":standard("Green Energy & Sustainable Design","Sustainability","Engineering support for efficient buildings and renewable-energy integration.","Energy audits, modelling and sustainable design reviews help identify practical opportunities to improve performance.",lib.rooftopSolarArray,["Energy audits","LEED-aligned design support","eQuest energy modelling","Renewable-energy integration","Building energy-performance review"]),
 "/services/sustainability/earthing-lightning-protection":standard("Earthing & Lightning Protection","Sustainability","Design and assessment of grounding and lightning-protection systems.","Proper earthing and lightning protection help manage fault current, touch potential and transient risk across electrical installations.",lib.latticeTower,["Earthing-system design","Soil resistivity assessment","Earth-grid calculations","Lightning-risk assessment","Protection-system inspection and testing"]),
 "/services/asset-integrity/risk-based-inspection":standard("Risk-Based Inspection (RBI)","Asset Integrity","A structured approach to prioritising inspection by risk.","RBI combines likelihood and consequence considerations to focus inspection resources on equipment requiring the greatest attention. Detailed TreeQ delivery scope requires client approval.",lib.industrialMachineryPanel,["Risk screening","Equipment criticality review","Inspection prioritisation","Review against applicable API guidance"]),
 "/services/asset-integrity/asset-integrity-assessment":standard("Asset Integrity Assessment","Asset Integrity","Structured review of asset condition, risk and available evidence.","Assessment scope is defined around the asset, operating environment and available inspection records.",lib.petrochemicalNight,["Condition review","Data and documentation review","Degradation-mechanism screening","Priority recommendations"]),
 "/services/asset-integrity/inspection-planning":standard("Inspection Planning","Asset Integrity","Focused inspection plans aligned with equipment condition and risk.","Inspection planning turns available technical evidence into a clear programme of methods, intervals and priorities.",lib.industrialWorkshop,["Inspection scope development","Method selection","Interval review","Priority and access planning"]),
 "/services/asset-integrity/asset-integrity-management":standard("Asset Integrity Management","Asset Integrity","Lifecycle coordination for critical equipment and systems.","A structured integrity-management approach connects inspection evidence, maintenance priorities and engineering decisions.",lib.refineryDusk,["Integrity strategy support","Inspection and maintenance coordination","Technical record review","Lifecycle action planning"]),
 "/solutions":standard("Integrated solutions for power, control and buildings.","Solutions","Explore TreeQ Power systems for electrical distribution, automation, power quality and building technology.","Our solutions portfolio brings together electrical equipment, controls, protection, energy systems and building services around the project requirement.",lib.transmissionTowerSky,["Power Systems","Automation & Control","Power Quality","Building Technology"],"Four solution families"),
 "/solutions/power-systems/hv-switchgear-transformers":standard("HV Switchgear & Transformers","Power Systems","Equipment and engineered packages for high- and medium-voltage distribution.","TreeQ Power’s documented scope includes air- and gas-insulated switchgear, ring main units, transformers and associated protection systems.",lib.hvInsulators,["Air- and gas-insulated MV switchgear from 3.3 kV to 33 kV","Ring main units","Power and distribution transformers","Protection relays","Capacitor banks and neutral-earthing resistors","DC and UPS systems"]),
 "/solutions/power-systems/lv-switchgear-busducts":standard("LV Switchgear & Busducts","Power Systems","Low-voltage distribution assemblies and busduct solutions.","Our scope covers engineered LV panels, distribution systems and related testing for industrial and building applications.",lib.lvDistributionPanel,["Main and sub-main distribution boards","Motor-control centres","Automatic power-factor correction panels","Busduct systems","Primary and secondary injection testing","Insulation-resistance testing"]),
 "/solutions/automation-control/industrial-automation":standard("Industrial Automation","Automation & Control","Control systems that connect plant equipment, process visibility and operator action.","TreeQ Power supports industrial automation systems for oil and gas, petrochemical, power, utilities, metals, cement and infrastructure environments.",lib.dataHallBlue,["PLC systems","SCADA systems","DCS panels","VFD and soft-starter panels","Control-panel integration","System testing and commissioning"]),
 "/solutions/automation-control/instrumentation":standard("Instrumentation","Automation & Control","Measurement and control support for industrial processes.","Instrumentation solutions support reliable measurement, monitoring and control across oil, power, water, petrochemical and gas applications.",lib.pressureInstrumentation,["Field instrumentation","Measurement systems","Control integration","Installation and commissioning support"]),
 "/solutions/power-quality/battery-ups":standard("Battery & UPS","Power Quality","Stored-energy and uninterrupted-power solutions for critical loads.","TreeQ Power supports industrial battery, charger and UPS requirements for utility, process and infrastructure environments.",lib.dataCentreRacks,["Nickel-cadmium and lead-acid batteries","Industrial battery chargers","AC and DC UPS systems","Battery testing and load-bank support","Installation and commissioning"]),
 "/solutions/building-technology/hvac":standard("HVAC","Building Technology","Mechanical systems for controlled, efficient indoor environments.","HVAC scope spans core air-handling, cooling and terminal equipment for commercial and industrial buildings.",lib.mechanicalPlantRoom,["Air-handling and fresh-air-handling units","Chillers and cooling towers","Fan-coil units","Condensing units","Installation and maintenance support"]),
 "/solutions/building-technology/lighting-controls":standard("Lighting & Lighting Controls","Building Technology","Indoor, outdoor and street-lighting solutions with coordinated controls.","TreeQ Power supports lighting selection, supply, installation and controls as part of integrated building and infrastructure systems.",lib.infrastructureInterchange,["Indoor and outdoor lighting","Street lighting","Lighting-control systems","Turnkey supply and installation","Testing and commissioning"]),
 "/solutions/building-technology/building-technologies":standard("Building Technologies","Building Technology","Integrated ELV, life-safety and communications systems.","Building-technology solutions bring together essential monitoring, access, communications and fire-safety infrastructure.",lib.dubaiMarinaNight,["Fire detection and voice evacuation","Sprinkler-system coordination","CCTV and access control","Structured cabling","Public-address systems"]),
 "/solutions/building-technology/renewable-energy":standard("Renewable Energy","Building Technology","Solar-power solutions for buildings, infrastructure and remote applications.","TreeQ Power’s documented renewable scope includes on-grid, off-grid and specialised solar systems.",lib.solarInstallationTeam,["Rooftop solar PV","On-grid and off-grid systems","Solar carports","Solar street lighting","Solar water-pumping systems","Telecommunications solar power"]),
};
const inds={"oil-gas":["Instrumentation and controls","Automation systems","Battery and UPS","Inspection and integrity support"],industrial:["Power distribution","Motor control and drives","Automation and instrumentation","Maintenance and testing"],commercial:["LV distribution","HVAC","Lighting and controls","ELV and fire systems"],infrastructure:["Power systems","Street lighting","Automation","Renewable-energy applications"],utilities:["HV and MV systems","Substation field services","Battery and charger systems","Testing and commissioning"]};
const indImages:Record<string,string>={"oil-gas":homeImages.engineer,industrial:lib.steelLifting,commercial:homeImages.commercial,infrastructure:lib.towerCraneCabin,utilities:lib.transmissionDusk};
for(const [slug,items] of Object.entries(inds)){const title=slug==="oil-gas"?"Oil & Gas":slug[0]!.toUpperCase()+slug.slice(1);pages[`/industries/${slug}`]=standard(title,"Industries",`${title} electrical engineering and technical support from TreeQ Power.`,`TreeQ Power’s verified technical disciplines can be configured around the operating requirements of ${title.toLowerCase()} environments.`,indImages[slug]!,items,"Relevant capabilities")}
pages["/industries"]=standard("Industries served by connected expertise.","Industries","TreeQ Power capabilities for oil and gas, industrial, commercial, infrastructure and utility environments.","Each operating environment places different demands on power, control and building systems. Our role is to align the relevant engineering, equipment and field services around those demands.",lib.transmissionSunset,Object.keys(inds).map(x=>x==="oil-gas"?"Oil & Gas":x[0]!.toUpperCase()+x.slice(1)),"Operating environments");
pages["/resources/blogs"]={title:"Blogs",eyebrow:"Blogs",description:"TreeQ Power insights and technical updates.",intro:"Coming soon.",image:homeImages.building,imageAlt:"TreeQ Power blogs",sections:[]};
pages["/resources/downloads"]={title:"Downloads",eyebrow:"Downloads",description:"TreeQ Power technical brochures and company information.",intro:"Coming soon.",image:homeImages.renewables,imageAlt:"TreeQ Power downloads",sections:[]};
pages["/resources/faqs"]={title:"Frequently asked questions.",eyebrow:"Resources",description:"Practical answers about TreeQ Power services and solutions.",intro:"These answers reflect the technical scope supplied for the website. Final project suitability is always established through technical review.",image:homeImages.inspection,imageAlt:"Electrical engineering detail",sections:[{title:"Services",body:"TreeQ Power covers engineering and design, consultancy, site services, testing and inspection, cable fault location, sustainability and asset-integrity support.",items:["What voltage levels are supported? — Site services cover equipment from 400 kV to 0.415 kV.","What cable services are available? — Fault and sheath location up to 132 kV, with jointing and termination up to 33 kV.","Is testing equipment available? — The documented inventory includes injection test sets, analyzers, thermal cameras, HV equipment and load banks."]},{title:"Solutions",body:"Power systems, automation, power quality and building technology are coordinated around the application.",items:["Are engineering studies available? — Yes, including load flow, short circuit, coordination, harmonics, voltage drop and arc flash.","Does TreeQ Power support renewables? — The documented scope includes rooftop, off-grid and specialised solar systems."]}]};
pages["/contact"]={title:"Let’s discuss the requirement.",eyebrow:"Contact",description:"Contact TreeQ Power in Dubai for electrical engineering, services and solutions.",intro:"Share the system, site and support needed. The TreeQ Power team can review the requirement and identify the relevant technical scope.",image:images.powerlines,imageAlt:"Power infrastructure at sunset",sections:[{title:"Contact details",body:"TreeQ Power Electromechanical Works, Al Qusais Industrial Area, Al Twar Fourth, Dubai, UAE.",items:["Phone: +971 55 948 9080","Email: raj@treeqpower.com","P.O. Box: 239085, Dubai, UAE","Hours: Monday–Friday, 08:00–17:00"]}],note:"[CONTACT DETAILS REQUIRE FINAL CLIENT CONFIRMATION]"};

pages["/our-services"]={title:"Integrated Engineering & Technical Services",eyebrow:"Our Services",description:"TreeQ Power provides electrical engineering, consultancy, field services, testing, inspection, cable fault location, generator and load bank services, asset integrity and sustainable energy solutions across the UAE.",intro:"Engineering-led electrical, electromechanical, testing, inspection, field service, asset integrity and sustainable energy support for commercial, industrial, infrastructure, utility and energy applications.",image:images.field,imageAlt:"Industrial electrical inspection and testing services",sections:[]};
pages["/our-services/asset-integrity"]={title:"Asset Integrity Services",eyebrow:"Asset Integrity",description:"Risk-based inspection, assessment, planning and integrity management services from TreeQ Power.",intro:"TreeQ Power provides structured asset integrity services to support equipment condition, risk prioritization, inspection strategy and lifecycle decisions.",image:images.industrial,imageAlt:"Industrial asset integrity inspection",sections:[{title:"Connected integrity services",body:"Asset integrity support can combine asset information, inspection history, failure mechanisms, condition, criticality and operational considerations.",items:["Risk-Based Inspection","Asset Integrity Assessment","Inspection Planning","Asset Integrity Management"]}]};
const serviceAliases:Record<string,string>={
 "/our-services/engineering-design":"/services/engineering/engineering-design",
 "/our-services/consultancy-services":"/services/engineering/consultancy",
 "/our-services/technical-field-services-electrical":"/services/field-maintenance/electrical-site-services",
 "/our-services/electronic-repair-maintenance":"/services/field-maintenance/electronics-repair-maintenance",
 "/our-services/generator-load-bank-services":"/services/field-maintenance/generator-load-bank-services",
 "/our-services/testing-equipment-rental":"/services/testing-inspection/testing-equipment-rental",
 "/our-services/third-party-inspection":"/services/testing-inspection/third-party-inspection",
 "/our-services/cable-fault-location":"/services/testing-inspection/cable-fault-location",
 "/our-services/green-energy-sustainable-design":"/services/sustainability/green-energy-sustainable-design",
 "/our-services/earthing-lightning-protection":"/services/sustainability/earthing-lightning-protection",
 "/our-services/asset-integrity/risk-based-inspection":"/services/asset-integrity/risk-based-inspection",
 "/our-services/asset-integrity/asset-integrity-assessment":"/services/asset-integrity/asset-integrity-assessment",
 "/our-services/asset-integrity/inspection-planning":"/services/asset-integrity/inspection-planning",
 "/our-services/asset-integrity/asset-integrity-management":"/services/asset-integrity/asset-integrity-management",
};
for(const [alias,source] of Object.entries(serviceAliases)){const page=pages[source];if(page)pages[alias]=page}
