import { ArrowDown, ArrowRight, FileCheck2, Handshake, Layers3, Users } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { SiteLink } from "@/components/site-link";
import {
  aboutApproach,
  aboutCapabilities,
  aboutFaqs,
  aboutImages,
  aboutIndustries,
  aboutReasons,
  aboutValues,
  lifecycle,
} from "@/lib/about-content";

function Heading({ eyebrow, title, intro }: { eyebrow?: string; title: string; intro?: string }) {
  return <div className="about-heading">{eyebrow && <p className="zoho-kicker">{eyebrow}</p>}<h2>{title}</h2>{intro && <p>{intro}</p>}</div>;
}

export function AboutPage() {
  return <main>
    <section className="about-hero"><img src={aboutImages.hero} alt="TreeQ Power engineering and electrical solutions in the UAE" width="1800" height="1200"/><div className="about-hero-wash"/><div className="zoho-shell about-hero-copy reveal"><p className="zoho-kicker">About TreeQ Power</p><h1>Engineering, Electrical & Electromechanical Expertise for the UAE</h1><p>TreeQ Power delivers integrated engineering, electrical, MEP, power systems, automation, testing, inspection, maintenance and asset integrity solutions for commercial, industrial, infrastructure, utility and energy applications.</p><div><Button size="lg" asChild><SiteLink to="/services">Explore Our Services<ArrowRight/></SiteLink></Button><Button size="lg" variant="outline" asChild><SiteLink to="/contact">Contact TreeQ Power</SiteLink></Button></div></div></section>

    <nav className="about-jump reveal" aria-label="About page sections"><div className="zoho-shell"><span>Explore TreeQ Power</span><a href="#company">Company</a><a href="#capabilities">Capabilities</a><a href="#approach">Approach</a><a href="#industries">Industries</a><a href="#values">Values</a><a href="#faq">FAQs</a></div></nav>

    <section id="company" className="about-overview reveal"><div className="zoho-shell about-overview-grid"><div><Heading eyebrow="Company Overview" title="Integrated Technical Solutions for the Asset Lifecycle"/><div className="about-body"><p>TreeQ Power Electromechanical Works is a Dubai-based technical solutions company serving electrical, electromechanical, MEP, power, automation, testing, inspection, maintenance and asset integrity requirements.</p><p>Our service capabilities extend across engineering and design, consultancy, technical field services, electrical testing and diagnostics, generator and load bank services, testing equipment rental, third-party inspection, cable fault testing, sustainable energy and asset integrity management.</p><p>Our solutions portfolio also covers HV/MV/LV switchgear, transformers, busducts, industrial automation, instrumentation, battery and UPS systems, HVAC, lighting, building technologies and renewable energy.</p><p>By combining engineering capability with practical field support, TreeQ Power aims to provide solutions that are technically appropriate, operationally practical and aligned with project and asset requirements.</p></div><Button variant="outline" asChild><SiteLink to="/about-us/company-overview">Read the Company Overview<ArrowRight/></SiteLink></Button></div><figure><img src={aboutImages.overview} alt="Industrial electrical and electromechanical engineering systems" loading="lazy" width="900" height="700"/><figcaption>Engineering capability connected to practical field support.</figcaption></figure></div></section>

    <section className="about-experience reveal"><div className="zoho-shell about-experience-grid"><div className="about-experience-image"><img src={aboutImages.experience} alt="Industrial power and engineering infrastructure" loading="lazy" width="1000" height="760"/></div><div><Heading eyebrow="Experience" title="More Than Two Decades of Technical Experience"/><div className="about-body"><p>TreeQ Power’s roots extend back to 2002, representing more than two decades of involvement in electrical, electromechanical and technical service requirements.</p><p>Over this period, the company’s capabilities have developed across engineering, electrical systems, field services, testing and commissioning, maintenance, automation, MEP, inspection and technical support.</p><p>Today, TreeQ Power’s service portfolio is structured to support clients across multiple stages of the asset lifecycle — from engineering and implementation to maintenance, diagnostics, refurbishment and integrity-focused activities.</p></div></div></div></section>

    <section id="capabilities" className="about-capabilities reveal"><div className="zoho-shell"><Heading eyebrow="Our Capabilities" title="From Engineering & Design to Lifecycle Support" intro="Six connected technical disciplines allow TreeQ Power to support systems from early engineering through field execution, verification and long-term asset care."/><div className="about-capability-grid">{aboutCapabilities.map(({ title, items, to, icon: Icon }, index) => <SiteLink to={to} className="about-capability-card" key={title}><div><span>{String(index + 1).padStart(2,"0")}</span><Icon/></div><h3>{title}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><strong>Explore capability <ArrowRight/></strong></SiteLink>)}</div></div></section>

    <section className="about-engineering reveal"><div className="zoho-shell about-engineering-grid"><div><img src={aboutImages.approach} alt="Engineer reviewing electrical engineering and technical systems" loading="lazy" width="900" height="700"/></div><div><Heading title="Engineering That Connects Design, Execution and Operations"/><div className="about-body"><p>Electrical and electromechanical systems do not operate in isolation. Their performance depends on design, equipment selection, installation quality, testing, commissioning, operating conditions, maintenance and the condition of connected assets.</p><p>TreeQ Power’s approach brings these considerations together by combining engineering studies, technical field services, testing, diagnostics, maintenance and asset-focused support.</p><p>This creates a complete technical capability rather than presenting individual services as disconnected offerings.</p></div><Button variant="outline" asChild><SiteLink to="/services/engineering/engineering-design">Explore Engineering & Design Services<ArrowRight/></SiteLink></Button></div></div></section>

    <section id="approach" className="about-process reveal"><div className="zoho-shell"><Heading eyebrow="Our Project Approach" title="A Practical Approach to Technical Delivery"/><ol>{aboutApproach.map(item => <li key={item.number}><span>{item.number}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></li>)}</ol></div></section>

    <section id="industries" className="about-industries reveal"><div className="zoho-shell"><Heading eyebrow="Industries We Support" title="Supporting Diverse Industrial & Infrastructure Environments" intro="TreeQ Power supports technical requirements across a range of operating environments, with services and solutions selected according to the project’s technical, operational and asset requirements."/><div className="about-industry-grid">{aboutIndustries.map(item => <SiteLink to={item.to} key={item.title}><img src={item.image} alt={item.alt} loading="lazy" width="650" height="760"/><div><h3>{item.title}</h3><ArrowRight/></div></SiteLink>)}</div><Button variant="outline" asChild><SiteLink to="/industries">Explore Supported Industries<ArrowRight/></SiteLink></Button></div></section>

    <section className="about-why reveal"><div className="zoho-shell"><div className="about-why-intro"><Heading eyebrow="Why TreeQ Power" title="One Partner Across Multiple Technical Disciplines"/><Button variant="outline" asChild><SiteLink to="/about-us/why-treeq-power">Why TreeQ Power<ArrowRight/></SiteLink></Button></div><div className="about-reason-grid">{aboutReasons.map(item => <article key={item.number}><span>{item.number}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>

    <section className="about-mission reveal"><div className="zoho-shell about-mission-grid"><div><p className="zoho-kicker">Our Mission</p><h2>Deliver Practical Technical Solutions That Support Reliable Operations</h2></div><div><p>Our mission is to provide technically sound, practical and responsive engineering and electromechanical solutions that help clients install, operate, maintain and improve critical systems and assets.</p><p>We focus on understanding the technical requirement, applying appropriate engineering practices and supporting reliable field execution throughout the relevant stage of the asset lifecycle.</p></div></div></section>

    <section id="values" className="about-values reveal"><div className="zoho-shell"><Heading title="Our Core Values"/><div>{aboutValues.map(({ title, text, icon: Icon }, index) => <article key={title}><span>{String(index + 1).padStart(2,"0")}</span><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="about-credentials reveal"><div className="zoho-shell"><div className="about-teaser about-teaser-large"><img src={aboutImages.compliance} alt="Technical inspection and engineering compliance document review" loading="lazy" width="900" height="700"/><div><FileCheck2/><p className="zoho-kicker">Certifications & Technical Compliance</p><h2>Qualifications, Certifications & Technical Credentials</h2><p>TreeQ Power’s certifications, approvals, registrations and technical credentials will be presented here as verified documentation becomes available. The website will display only credentials that are currently valid and confirmed by the client.</p><Button variant="outline" asChild><SiteLink to="/about-us/certifications">View Certifications<ArrowRight/></SiteLink></Button></div></div><div className="about-teaser-pair"><article><Handshake/><h2>Clients & Partners</h2><p>TreeQ Power works across technical environments where reliable electrical, electromechanical and engineering support is required. Verified client and partner information will be presented as approved by the client.</p><Button variant="link" asChild><SiteLink to="/about-us/clients-partners">View Clients & Partners<ArrowRight/></SiteLink></Button></article><article><Layers3/><h2>Technology & Equipment Ecosystem</h2><p>TreeQ Power works with equipment and technology across electrical power, automation, drives, controls, instrumentation and industrial systems. Manufacturer relationships will be stated only after verification.</p><Button variant="link" asChild><SiteLink to="/about-us/brands">Explore Brands<ArrowRight/></SiteLink></Button></article></div></div></section>

    <section className="about-team reveal"><div className="zoho-shell about-team-grid"><div><img src={aboutImages.team} alt="Licensed photograph representing industrial engineering collaboration" loading="lazy" width="900" height="700"/><small>Representative licensed engineering image; people shown are not identified as TreeQ Power personnel.</small></div><div><Users/><Heading title="Engineering & Technical Team"/><p>TreeQ Power’s services are supported by engineering, technical and field personnel working across project delivery, electrical systems, maintenance, testing, inspection and technical support.</p><p>Individual employee profiles will be presented only when approved information and photographs are supplied by the client.</p></div></div></section>

    <section className="about-lifecycle reveal"><div className="zoho-shell"><Heading eyebrow="Complete Technical Capability" title="One Connected Asset Lifecycle"/><div>{lifecycle.map(({ title, icon: Icon }, index) => <article key={title}><Icon/><span>{title}</span>{index < lifecycle.length - 1 && <ArrowDown/>}</article>)}</div></div></section>

    <section id="faq" className="about-faq reveal"><div className="zoho-shell about-faq-grid"><div><Heading eyebrow="Frequently Asked Questions" title="About TreeQ Power — Frequently Asked Questions"/><Button variant="outline" asChild><SiteLink to="/resources/faqs">View All FAQs<ArrowRight/></SiteLink></Button></div><Accordion type="single" collapsible>{aboutFaqs.map((item,index) => <AccordionItem value={`about-faq-${index}`} key={item.question}><AccordionTrigger><span><small>{String(index + 1).padStart(2,"0")}</small>{item.question}</span></AccordionTrigger><AccordionContent><p>{item.answer}</p></AccordionContent></AccordionItem>)}</Accordion></div></section>

    <section className="about-final reveal"><img src={aboutImages.hero} alt="" loading="lazy" width="1800" height="1200"/><div className="about-final-wash"/><div className="zoho-shell"><p className="zoho-kicker">Work With TreeQ Power</p><h2>Have a Technical Requirement?</h2><p>Whether you are planning a new project, assessing an existing system, addressing an equipment issue or looking for ongoing technical support, TreeQ Power can help identify the appropriate service or solution pathway.</p><div><Button size="lg" asChild><SiteLink to="/contact">Request a Consultation<ArrowRight/></SiteLink></Button><Button size="lg" variant="outline" asChild><SiteLink to="/services">Explore Our Services</SiteLink></Button></div></div></section>
  </main>;
}