import { ArrowRight, BatteryCharging, Building2, CircuitBoard, Factory, Gauge, ScanLine, ShieldCheck, SunMedium, Wrench, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteLink } from "@/components/site-link";
import { images } from "@/lib/site-data";
const capabilities=[
 {title:"Engineering & Design",text:"Power-system studies, protection, power quality and coordinated system design.",to:"/services/engineering/engineering-design",icon:CircuitBoard},
 {title:"Field & Maintenance",text:"Installation, commissioning, troubleshooting and maintenance for critical equipment.",to:"/services/field-maintenance/electrical-site-services",icon:Wrench},
 {title:"Testing & Inspection",text:"Specialist testing, inspection and cable-fault location for informed decisions.",to:"/services/testing-inspection/third-party-inspection",icon:ScanLine},
 {title:"Sustainability",text:"Energy analysis, efficient design, earthing and renewable-energy support.",to:"/services/sustainability/green-energy-sustainable-design",icon:SunMedium},
];
const solutions=[{title:"Power Systems",to:"/solutions/power-systems/hv-switchgear-transformers",icon:Zap},{title:"Automation & Control",to:"/solutions/automation-control/industrial-automation",icon:Gauge},{title:"Power Quality",to:"/solutions/power-quality/battery-ups",icon:BatteryCharging},{title:"Building Technology",to:"/solutions/building-technology/building-technologies",icon:Building2}];
export function HomePage(){return <main><section className="home-photo-hero"><img src={images.hero} alt="High-voltage power infrastructure"/><div className="home-photo-wash"/><div className="zoho-shell home-photo-copy reveal"><p className="zoho-kicker">TreeQ Power Electromechanical</p><h1>Engineering power.<span>Supporting every stage.</span></h1><p>Electrical engineering, field services, testing, inspection and integrated solutions from Dubai, UAE.</p><div><Button size="lg" asChild><SiteLink to="/services">Explore services<ArrowRight/></SiteLink></Button><Button size="lg" variant="outline" className="home-hero-ghost" asChild><SiteLink to="/contact">Start an enquiry</SiteLink></Button></div></div></section><section className="home-capabilities reveal"><div className="zoho-shell"><div className="home-section-head"><p className="zoho-kicker">Connected expertise</p><h2>One technical partner across the asset lifecycle.</h2><p>From studies and design through commissioning, maintenance and integrity support.</p></div><div className="home-card-grid">{capabilities.map(({title,text,to,icon:Icon})=><SiteLink to={to} className="home-card" key={title}><Icon/><h3>{title}</h3><p>{text}</p><ArrowRight/></SiteLink>)}</div><Button variant="outline" asChild><SiteLink to="/services">View all services<ArrowRight/></SiteLink></Button></div></section><section className="home-solutions reveal"><div className="zoho-shell home-solutions-grid"><div><p className="zoho-kicker">Integrated solutions</p><h2>Power, control and buildings—coordinated.</h2><p>Explore engineered equipment and integrated systems aligned around each application.</p><Button variant="outline" asChild><SiteLink to="/solutions">Explore solutions<ArrowRight/></SiteLink></Button></div><div>{solutions.map(({title,to,icon:Icon})=><SiteLink to={to} key={title}><Icon/><span>{title}</span><ArrowRight/></SiteLink>)}</div></div></section><section className="home-industry reveal"><div className="zoho-shell"><div><Factory/><p className="zoho-kicker">Operating environments</p><h2>Technical capability for demanding sites.</h2></div><div><p>TreeQ Power’s disciplines support oil and gas, industrial, commercial, infrastructure and utility requirements.</p><Button asChild><SiteLink to="/industries">Explore industries<ArrowRight/></SiteLink></Button></div></div></section><section className="home-final reveal"><div className="zoho-shell"><ShieldCheck/><h2>Bring us the technical requirement.</h2><p>We’ll help identify the engineering, equipment and field support required.</p><Button size="lg" asChild><SiteLink to="/contact">Contact TreeQ Power<ArrowRight/></SiteLink></Button></div></section></main>}
