import { Phone, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteLink } from "@/components/site-link";
import { coreCapabilities, industries } from "@/lib/home-content";
import { lib } from "@/lib/image-library";
import { images } from "@/lib/site-data";

function SectionHeading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) {
  return <div className="home-heading"><p className="zoho-kicker">{eyebrow}</p><h2>{title}</h2>{intro && <p>{intro}</p>}</div>;
}

export function HomePage() {
  return <main>
    <section className="home-photo-hero"><img src={images.hero} alt="High-voltage power infrastructure"/><div className="home-photo-wash"/><div className="zoho-shell home-photo-copy reveal"><p className="zoho-kicker">TreeQ Power Electromechanical</p><h1>Engineering power.<span>Supporting every stage.</span></h1><p>Electrical engineering, field services, testing, inspection and integrated solutions from Dubai, UAE.</p><div><Button size="lg" asChild><SiteLink to="/services">Explore services</SiteLink></Button><Button size="lg" variant="outline" className="home-hero-ghost" asChild><SiteLink to="/contact">Start an enquiry</SiteLink></Button></div></div></section>

    <section className="home-about reveal"><div className="zoho-shell home-split"><div className="home-media"><img src={lib.electricalTechnician} alt="Electrical engineer inspecting industrial power equipment" loading="lazy" width="900" height="700"/><span>Engineering / Field execution / Lifecycle support</span></div><div><SectionHeading eyebrow="About TreeQ Power" title="Engineering Expertise Across the Asset Lifecycle"/><div className="home-rich-copy"><p>TreeQ Power provides integrated technical solutions covering the complete lifecycle of electrical, electromechanical and industrial assets — from engineering and design through supply, installation, testing, commissioning, maintenance, refurbishment and technical support.</p><p>Our capabilities span electrical power systems, MEP services, industrial automation, instrumentation, testing and diagnostics, generator and load bank services, cable fault testing, third-party inspection, sustainable energy solutions and asset integrity management.</p><p>With a focus on engineering quality, technical reliability and practical field execution, TreeQ Power supports clients across commercial, industrial, infrastructure, utilities and energy environments in the UAE.</p></div><Button variant="outline" asChild><SiteLink to="/about-us">Discover TreeQ Power</SiteLink></Button></div></div></section>

    <section className="home-core reveal"><div className="zoho-shell"><SectionHeading eyebrow="What We Do" title="Three Core Service Divisions. One Technical Partner." intro="TreeQ Power delivers inspection and verification, asset integrity and electrical & automation services — supporting clients from project execution through lifecycle asset support."/><div className="home-core-grid home-core-grid-3">{coreCapabilities.map(({ title, text, to, image, imageAlt }, index) => <SiteLink to={to} className="home-core-card" key={title}>{image && <img className="home-core-bg" src={image} alt={imageAlt} loading="lazy" width="1600" height="1067" />}<span className="home-core-veil" aria-hidden="true"></span><span className="home-core-index">{String(index + 1).padStart(2, "0")}</span><div className="home-core-copy"><h3>{title}</h3><p>{text}</p></div><span className="home-core-action">Explore service</span></SiteLink>)}</div><div className="home-core-note"><span>TreeQ Power / Core services</span><span>Inspection · Asset integrity · Electrical &amp; automation</span></div></div></section>

    <section className="home-industries-new reveal"><div className="zoho-shell"><SectionHeading eyebrow="Industries We Support" title="Solutions Designed Around Industry Requirements"/><div className="home-industry-cards">{industries.map(item => <SiteLink to={item.to} className="home-industry-card" key={item.title}><img src={item.image} alt={item.imageAlt} loading="lazy" width="700" height="760"/><div><span>{item.title}</span><p>{item.text}</p></div></SiteLink>)}</div></div></section>

    <section className="home-final-new reveal"><div className="zoho-shell"><p className="zoho-kicker">Let’s Discuss Your Requirements</p><ShieldCheck/><h2>Need Engineering, Electrical or Technical Support?</h2><p>Tell us about your project, facility, equipment or technical requirement. Our team can help identify the appropriate engineering, service or solution pathway for your needs.</p><div><Button size="lg" asChild><SiteLink to="/contact">Request a Consultation</SiteLink></Button><Button size="lg" variant="outline" asChild><SiteLink to="/contact"><Phone/>Contact Us</SiteLink></Button></div><address>TreeQ Power Electromechanical Works · Dubai, United Arab Emirates · P.O. Box 239085 · +971 55 948 9080 · Monday–Friday, 08:00 AM–05:00 PM</address></div></section>
  </main>;
}
